version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bekosher-postgres
    restart: always
    environment:
      POSTGRES_DB: bekosher
      POSTGRES_USER: bekosher_user
      POSTGRES_PASSWORD: bekosher_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 